services:
  - type: web
    name: veriflow-backend
    runtime: node
    plan: starter
    autoDeploy: true
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: API_PREFIX
        value: /api/v1
      - key: TRUST_PROXY
        value: "true"
      - key: REQUEST_SIZE_LIMIT
        value: 10mb
      - key: LOG_LEVEL
        value: info
      - key: COOKIE_SECURE
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_FOLDER
        value: veriflow
      - key: PUBLIC_VERIFY_BASE_URL
        sync: false
      - key: OCR_LANG_1
        value: eng
