export const apiEndpoints = {
  health: '/health',
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    me: '/auth/me',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    seedSuperAdmin: '/auth/seed-super-admin',
  },
  graduates: {
    list: '/graduates',
    filtersMetadata: '/graduates/filters/metadata',
    detail: (graduateId: string) => `/graduates/${graduateId}`,
    profile: (graduateId: string) => `/graduates/${graduateId}/profile`,
    create: '/graduates',
    update: (graduateId: string) => `/graduates/${graduateId}`,
    archive: (graduateId: string) => `/graduates/${graduateId}/archive`,
    unarchive: (graduateId: string) => `/graduates/${graduateId}/unarchive`,
    remove: (graduateId: string) => `/graduates/${graduateId}`,
    certificates: (graduateId: string) => `/certificates/graduate/${graduateId}`,
  },
  institutions: {
    list: '/institutions',
    detail: (institutionId: string) => `/institutions/${institutionId}`,
    create: '/institutions',
    update: (institutionId: string) => `/institutions/${institutionId}`,
    updateStatus: (institutionId: string) => `/institutions/${institutionId}/status`,
    remove: (institutionId: string) => `/institutions/${institutionId}`,
  },
  certificates: {
    list: '/certificates',
    filtersMetadata: '/certificates/filters/metadata',
    detail: (certificateId: string) => `/certificates/${certificateId}`,
    preview: (certificateId: string) => `/certificates/${certificateId}/preview`,
    create: '/certificates',
    uploadMetadata: '/certificates/upload/metadata',
    update: (certificateId: string) => `/certificates/${certificateId}`,
    publish: (certificateId: string) => `/certificates/${certificateId}/publish`,
    revoke: (certificateId: string) => `/certificates/${certificateId}/revoke`,
    remove: (certificateId: string) => `/certificates/${certificateId}`,
    byGraduate: (graduateId: string) => `/certificates/graduate/${graduateId}`,
  },
  verifications: {
    list: '/verifications',
    detail: (verificationId: string) => `/verifications/${verificationId}`,
    lookupReference: (reference: string) => `/verifications/reference/${reference}`,
    verifyByNumber: '/verifications/public/number',
    verifyByUpload: '/verifications/public/upload',
    verifyByQr: '/verifications/public/qr',
    verifyPublic: '/verifications/public/verify',
    manual: (verificationId: string) => `/verifications/${verificationId}/manual`,
    byCertificate: (certificateId: string) => `/verifications/certificate/${certificateId}`,
    byGraduate: (graduateId: string) => `/verifications/graduate/${graduateId}`,
    metadata: '/verifications/metadata',
  },
  uploads: {
    publicVerify: '/uploads/public/verify',
    certificateOcr: '/uploads/certificate/ocr',
    certificateReOcr: (certificateId: string) => `/uploads/certificate/re-ocr/${certificateId}`,
    certificateCreate: '/uploads/certificate/create',
    graduateCertificate: (graduateId: string) => `/uploads/graduate/${graduateId}/certificate`,
    certificateCorrect: (certificateId: string) => `/uploads/certificate/${certificateId}/correct`,
    certificateRegenerateQr: (certificateId: string) => `/uploads/certificate/${certificateId}/qr/regenerate`,
    document: '/uploads/document',
  },
  auditLogs: {
    list: '/audit-logs',
    metadata: '/audit-logs/metadata',
    stats: '/audit-logs/stats',
    export: '/audit-logs/export',
    detail: (auditLogId: string) => `/audit-logs/${auditLogId}`,
    entity: (entityType: string, entityId: string) => `/audit-logs/entity/${entityType}/${entityId}`,
  },
  analytics: {
    dashboard: '/analytics/dashboard',
    system: '/analytics/system',
    publicStats: '/analytics/public/stats',
  },
  profile: {
    get: '/profile',
    updateUser: '/profile/user',
    updateInstitution: '/profile/institution',
    updatePassword: '/profile/password',
  },
} as const;
