/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates.$certificateId'
import { Route as CertificatesUploadRouteImport } from './routes/certificates.upload'
import { Route as GraduatesIndexRouteImport } from './routes/graduates.index'
import { Route as GraduatesNewRouteImport } from './routes/graduates.new'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyResultRouteImport } from './routes/verify.result'
import { Route as AdminInstitutionsIndexRouteImport } from './routes/admin.institutions.index'
import { Route as AdminInstitutionsNewRouteImport } from './routes/admin.institutions.new'
import { Route as GraduatesGraduateIdIndexRouteImport } from './routes/graduates.$graduateId.index'
import { Route as GraduatesGraduateIdEditRouteImport } from './routes/graduates.$graduateId.edit'
import { Route as AdminInstitutionsInstitutionIdIndexRouteImport } from './routes/admin.institutions.$institutionId.index'
import { Route as AdminInstitutionsInstitutionIdEditRouteImport } from './routes/admin.institutions.$institutionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificatesUploadRoute = CertificatesUploadRouteImport.update({
  id: '/certificates/upload',
  path: '/certificates/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesIndexRoute = GraduatesIndexRouteImport.update({
  id: '/graduates/',
  path: '/graduates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesNewRoute = GraduatesNewRouteImport.update({
  id: '/graduates/new',
  path: '/graduates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResultRoute = VerifyResultRouteImport.update({
  id: '/verify/result',
  path: '/verify/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionsIndexRoute = AdminInstitutionsIndexRouteImport.update({
  id: '/admin/institutions/',
  path: '/admin/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionsNewRoute = AdminInstitutionsNewRouteImport.update({
  id: '/admin/institutions/new',
  path: '/admin/institutions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesGraduateIdIndexRoute =
  GraduatesGraduateIdIndexRouteImport.update({
    id: '/graduates/$graduateId/',
    path: '/graduates/$graduateId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraduatesGraduateIdEditRoute = GraduatesGraduateIdEditRouteImport.update({
  id: '/graduates/$graduateId/edit',
  path: '/graduates/$graduateId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionsInstitutionIdIndexRoute =
  AdminInstitutionsInstitutionIdIndexRouteImport.update({
    id: '/admin/institutions/$institutionId/',
    path: '/admin/institutions/$institutionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInstitutionsInstitutionIdEditRoute =
  AdminInstitutionsInstitutionIdEditRouteImport.update({
    id: '/admin/institutions/$institutionId/edit',
    path: '/admin/institutions/$institutionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verifications': typeof VerificationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/upload': typeof CertificatesUploadRoute
  '/graduates/new': typeof GraduatesNewRoute
  '/verify/result': typeof VerifyResultRoute
  '/admin/': typeof AdminIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/graduates/': typeof GraduatesIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/graduates/$graduateId/edit': typeof GraduatesGraduateIdEditRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/graduates/$graduateId/': typeof GraduatesGraduateIdIndexRoute
  '/admin/institutions/$institutionId/edit': typeof AdminInstitutionsInstitutionIdEditRoute
  '/admin/institutions/$institutionId/': typeof AdminInstitutionsInstitutionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verifications': typeof VerificationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/upload': typeof CertificatesUploadRoute
  '/graduates/new': typeof GraduatesNewRoute
  '/verify/result': typeof VerifyResultRoute
  '/admin': typeof AdminIndexRoute
  '/certificates': typeof CertificatesIndexRoute
  '/graduates': typeof GraduatesIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/graduates/$graduateId/edit': typeof GraduatesGraduateIdEditRoute
  '/admin/institutions': typeof AdminInstitutionsIndexRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdIndexRoute
  '/admin/institutions/$institutionId/edit': typeof AdminInstitutionsInstitutionIdEditRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verifications': typeof VerificationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/upload': typeof CertificatesUploadRoute
  '/graduates/new': typeof GraduatesNewRoute
  '/verify/result': typeof VerifyResultRoute
  '/admin/': typeof AdminIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/graduates/': typeof GraduatesIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/graduates/$graduateId/edit': typeof GraduatesGraduateIdEditRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/graduates/$graduateId/': typeof GraduatesGraduateIdIndexRoute
  '/admin/institutions/$institutionId/edit': typeof AdminInstitutionsInstitutionIdEditRoute
  '/admin/institutions/$institutionId/': typeof AdminInstitutionsInstitutionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/unauthorized'
    | '/verifications'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/certificates/$certificateId'
    | '/certificates/upload'
    | '/graduates/new'
    | '/verify/result'
    | '/admin/'
    | '/certificates/'
    | '/graduates/'
    | '/verify/'
    | '/admin/institutions/new'
    | '/graduates/$graduateId/edit'
    | '/admin/institutions/'
    | '/graduates/$graduateId/'
    | '/admin/institutions/$institutionId/edit'
    | '/admin/institutions/$institutionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/unauthorized'
    | '/verifications'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/certificates/$certificateId'
    | '/certificates/upload'
    | '/graduates/new'
    | '/verify/result'
    | '/admin'
    | '/certificates'
    | '/graduates'
    | '/verify'
    | '/admin/institutions/new'
    | '/graduates/$graduateId/edit'
    | '/admin/institutions'
    | '/graduates/$graduateId'
    | '/admin/institutions/$institutionId/edit'
    | '/admin/institutions/$institutionId'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/settings'
    | '/unauthorized'
    | '/verifications'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/certificates/$certificateId'
    | '/certificates/upload'
    | '/graduates/new'
    | '/verify/result'
    | '/admin/'
    | '/certificates/'
    | '/graduates/'
    | '/verify/'
    | '/admin/institutions/new'
    | '/graduates/$graduateId/edit'
    | '/admin/institutions/'
    | '/graduates/$graduateId/'
    | '/admin/institutions/$institutionId/edit'
    | '/admin/institutions/$institutionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerificationsRoute: typeof VerificationsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CertificatesUploadRoute: typeof CertificatesUploadRoute
  GraduatesNewRoute: typeof GraduatesNewRoute
  VerifyResultRoute: typeof VerifyResultRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  GraduatesIndexRoute: typeof GraduatesIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  AdminInstitutionsNewRoute: typeof AdminInstitutionsNewRoute
  GraduatesGraduateIdEditRoute: typeof GraduatesGraduateIdEditRoute
  AdminInstitutionsIndexRoute: typeof AdminInstitutionsIndexRoute
  GraduatesGraduateIdIndexRoute: typeof GraduatesGraduateIdIndexRoute
  AdminInstitutionsInstitutionIdEditRoute: typeof AdminInstitutionsInstitutionIdEditRoute
  AdminInstitutionsInstitutionIdIndexRoute: typeof AdminInstitutionsInstitutionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/upload': {
      id: '/certificates/upload'
      path: '/certificates/upload'
      fullPath: '/certificates/upload'
      preLoaderRoute: typeof CertificatesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/': {
      id: '/graduates/'
      path: '/graduates'
      fullPath: '/graduates/'
      preLoaderRoute: typeof GraduatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/new': {
      id: '/graduates/new'
      path: '/graduates/new'
      fullPath: '/graduates/new'
      preLoaderRoute: typeof GraduatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/result': {
      id: '/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof VerifyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions/': {
      id: '/admin/institutions/'
      path: '/admin/institutions'
      fullPath: '/admin/institutions/'
      preLoaderRoute: typeof AdminInstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions/new': {
      id: '/admin/institutions/new'
      path: '/admin/institutions/new'
      fullPath: '/admin/institutions/new'
      preLoaderRoute: typeof AdminInstitutionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/$graduateId/': {
      id: '/graduates/$graduateId/'
      path: '/graduates/$graduateId'
      fullPath: '/graduates/$graduateId/'
      preLoaderRoute: typeof GraduatesGraduateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/$graduateId/edit': {
      id: '/graduates/$graduateId/edit'
      path: '/graduates/$graduateId/edit'
      fullPath: '/graduates/$graduateId/edit'
      preLoaderRoute: typeof GraduatesGraduateIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions/$institutionId/': {
      id: '/admin/institutions/$institutionId/'
      path: '/admin/institutions/$institutionId'
      fullPath: '/admin/institutions/$institutionId/'
      preLoaderRoute: typeof AdminInstitutionsInstitutionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions/$institutionId/edit': {
      id: '/admin/institutions/$institutionId/edit'
      path: '/admin/institutions/$institutionId/edit'
      fullPath: '/admin/institutions/$institutionId/edit'
      preLoaderRoute: typeof AdminInstitutionsInstitutionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerificationsRoute: VerificationsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CertificatesUploadRoute: CertificatesUploadRoute,
  GraduatesNewRoute: GraduatesNewRoute,
  VerifyResultRoute: VerifyResultRoute,
  AdminIndexRoute: AdminIndexRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  GraduatesIndexRoute: GraduatesIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  AdminInstitutionsNewRoute: AdminInstitutionsNewRoute,
  GraduatesGraduateIdEditRoute: GraduatesGraduateIdEditRoute,
  AdminInstitutionsIndexRoute: AdminInstitutionsIndexRoute,
  GraduatesGraduateIdIndexRoute: GraduatesGraduateIdIndexRoute,
  AdminInstitutionsInstitutionIdEditRoute:
    AdminInstitutionsInstitutionIdEditRoute,
  AdminInstitutionsInstitutionIdIndexRoute:
    AdminInstitutionsInstitutionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
